name: SocialMediaIE
channels:
  - defaults
  - conda-forge
  - pytorch
  - intel
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - tqdm
  - ipython
  - ipykernel
  - pytorch==1.0.0
  - cudatoolkit=9.0
  - mkl
  - intel-openmp
  - umap-learn
  - pip:
    - allennlp==0.8.3
